### ISSUE TITLE
请问这个是适合安装什么Mac oS 什么版本的？

### ISSUE THREAD

**Issue by fuqiao1a** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#1]

**Comment by zb2947244682** [comment]
> _No description provided._

这个人只看得懂英文。。。

**Comment by fuqiao1a** [comment]
Which Mac OS version is supported by this device, I have a USB error during the installation process.

**Comment by fuqiao1a** [comment]
Is it convenient to leave a mailbox exchange?

**Comment by fuqiao1a** [comment]
> _No description provided._

https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only/issues/1#issue-495247689

**Comment by fuqiao1a** [comment]
> > _未提供说明。_
> 
> [][

兄弟留个邮箱交流下？

**Comment by XenOriginal** [comment]
我自己安装到15a546d，理论上之前的也支持，但也许有voodooi2c的问题

**Comment by fuqiao1a** [comment]
> 我自己安装到15a546d，理论上之前的也支持，但也许有voodooi2c的问

**Comment by fuqiao1a** [comment]
找不到这个镜像哎。

**Comment by fuqiao1a** [comment]
我遇到的问题真的让人无语，机器是ruby i5 集显款的，安装过程中一直卡在USB上，过不去

**Comment by XenOriginal** [comment]
try to drop SSDT-UIAC.aml voodooi2c.kext

**Comment by XenOriginal** [comment]
you can install system with other available efi, and replace it after completed

**Comment by fuqiao1a** [comment]
> 您可以安装系统与其他可用的 efi，并更换完成后
alright, thank you very much

**Comment by tienskowl** [comment]
@fuqiao1a 老哥，你解决这个问题了么，我想买这一款装黑苹果用
