### ISSUE TITLE
已star 求大佬加把劲实现扬声播放

### ISSUE THREAD

**Issue by SilurianYang** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#14]
## 用了大佬这个确实分分钟装上，不过有以下几个问题
1. 快捷键控制屏幕亮度无效(小问题)
1. 扬声器无法工作(**大问题**)
1. 蓝牙无法工作(小问题)
1. 网卡就不用说了 我用的外置网卡

# 求大佬加把劲 搞定**扬声播放**，加油啊

**Comment by XenOriginal** [comment]
插上外置键盘可以设置f2 f3调亮度；
扬声器比较特殊，应该是没法用常规方法解决；
蓝牙网卡更换我说的那块就好；

**Comment by SilurianYang** [comment]
@XenOriginal   我觉得其他都无所谓   **除了那个外放的问题比较有用点** 2020 大佬加油！！！

**Comment by XenOriginal** [comment]
又试了一下驱动外放，基本宣告无解，在windows下只用微软原生驱动，发现和mac一样只有耳机没有外放。
根据实验大胆推测，外放经过了一层Intel的dsp，比较特殊，就算结点弄对也无济于事。

**Comment by a37324614** [comment]
我的想法是 通过linux进行移植  毕竟在ubuntu下 声卡是可以工作的

**Comment by Mike-hd123** [comment]
是的加了dsp，好像是dolby audio。仅扬声器。
![image](https://user-images.githubusercontent.com/50143395/82792825-8fa3f900-9ea2-11ea-9644-7505a28f63ea.png)
![image](https://user-images.githubusercontent.com/50143395/82792907-ac403100-9ea2-11ea-9ac2-34f845efba24.png)
