### ISSUE TITLE
Installation stops ; keyboard no response

### ISSUE THREAD

**Issue by kmchong** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#15]
![IMG_0022](https://user-images.githubusercontent.com/2275868/72948630-b6e99d00-3dc0-11ea-9151-aa2edc0a822e.jpeg)

Xiaomi Ruby 15.6"

**Comment by SilurianYang** [comment]
可以使用鼠标啊

**Comment by kmchong** [comment]
有線鼠标？

Regards,
Keith Chong

**Comment by SilurianYang** [comment]
我和你同样的设备 我忘记当时用的啥了 反正是鼠标键盘都能用 现在已经装上一个月的样子了

**Comment by kmchong** [comment]
我是用UniBeast USB 起動的！你用的是什麼？

Regards,
Keith Chong

**Comment by SilurianYang** [comment]
一样

**Comment by kmchong** [comment]
我裝多一點 1000 GB SSD 不和有沒有关係？

Regards,
Keith Chong

**Comment by SilurianYang** [comment]
没任何关系 你键盘不响应 试试鼠标

**Comment by kmchong** [comment]
找個有缐mouse 試試！

Regards,
Keith Chong

**Comment by SilurianYang** [comment]
祝你成功！

**Comment by kmchong** [comment]
用有缐 mouse 沒有問題了！

Regards,
Keith Chong

**Comment by SilurianYang** [comment]
@kmchong  可以 这是本人设备
![QQ图片20200210144916](https://user-images.githubusercontent.com/31280665/74127088-886b1f00-4c14-11ea-84a9-8875d54cf267.jpg)

**Comment by XenOriginal** [comment]
不影响 所有驱动都不需要装在系统里 只要装在引导clover里就好

**Comment by XenOriginal** [comment]
不过你的问题是安装的话，争取一下装上系统，后面就好整了
