### ISSUE TITLE
升级到 10.15.3 需注意的问题 

### ISSUE THREAD

**Issue by SilurianYang** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#16]
## 美滋滋的升级到 10.15.3 快乐到极致！！ 

> 各位老哥可以在此EFI的基础上无痛升级！ 感谢大佬！ 希望大佬继续努力整到完美

## 出现问题
* 耳机 外放都不行了（昨晚奇怪的发现，打开电脑居然能用耳机，后面重开又不行了）
* 网卡依旧使用的外设网卡
* 蓝牙不行！
![QQ20200208-112045](https://user-images.githubusercontent.com/31280665/74078470-f6bdaf00-4a65-11ea-94d0-3bbb1d7ffbf4.png)

**Comment by XenOriginal** [comment]
外放一直都不行啊，耳机没问题，注意冷启动防止寄存器污染。
