### ISSUE TITLE
感谢作者大大，不过Videoproc检测无法解码HEVC，在交流群里看到有人分享EFI可能解决了这个问题，可以参考一下

### ISSUE THREAD

**Issue by DreamStarX** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#17]
感谢大佬做的这个EFI很完美，非常好用，万分感谢。

不过不知道如何修复HEVC解码，看到群里的其他人分享H264 HEVC解码都可用的EFI，搬运一下吧，不过我无法启动，小白一枚，可能是不会用，看了一下别人好像是把机型修改为2019款Macbook解决的，因为从第七代以后才支持HEVC解码的，现在的为17款属于第七代所以没有支持？小白见解，仅限参考，感谢作者大大🤗

更新：小白仅搬运交流群内朋友分享的EFI，实际还是用Github上您的，因为更完善哈哈，感谢大大的付出，那位朋友更新了第二版，没有尝试，两个云盘文件相同。

蓝奏云：https://www.lanzous.com/b00z891cb  密码:5r2d
度盘链接: https://pan.baidu.com/s/1ircLvOTwXyqqm-2ecosl8g  提取码: vbac

图片来源于那位朋友![22FA938793E439A5E0A86966B5C8DE6E](https://user-images.githubusercontent.com/59681576/74239105-2395ee80-4d12-11ea-821c-0441e652d035.png)

**Comment by SilurianYang** [comment]
你这要求太高了  我们这个本子本来就不好搞  先把基础的整完美再整细节

**Comment by DreamStarX** [comment]
> 你这要求太高了我们这个本子本来就不好搞先把基础的整体完美再整细节

现在还是在用Github作者的EFI，很好用，i3版本可以日用啦，不过要插网线和耳机，可以说很舒服哈。另外键盘亮度控制我用这个软件的，你可以试试还不错，可以设置FN+F4/F5调节亮度。
![截屏2020-02-11下午9 18 59](https://user-images.githubusercontent.com/59681576/74240652-660cfa80-4d15-11ea-9c47-41b8351d07ed.png)

**Comment by SilurianYang** [comment]
@DreamStarX  加个qq 我们讨论下？ 1606726660

**Comment by DreamStarX** [comment]
> 1606726660 @DreamStarX 加个qq我们讨论下？

我提供给您EFI作者的QQ吧，我啥也不懂。2286191966，所在群聊为149664949

**Comment by XenOriginal** [comment]
好的 我看一下

**Comment by XenOriginal** [comment]
smbios和显卡确实是有关系的

**Comment by XenOriginal** [comment]
你自己买一张网卡好了 一百块也不是很贵

**Comment by XenOriginal** [comment]
> > 你这要求太高了我们这个本子本来就不好搞先把基础的整体完美再整细节
> 
> 现在还是在用Github作者的EFI，很好用，i3版本可以日用啦，不过要插网线和耳机，可以说很舒服哈。另外键盘亮度控制我用这个软件的，你可以试试还不错，可以设置FN+F4/F5调节亮度。
> ![截屏2020-02-11下午9 18 59](https://user-images.githubusercontent.com/59681576/74240652-660cfa80-4d15-11ea-9c47-41b8351d07ed.png)

你插个外接键盘就可以设置的

**Comment by XenOriginal** [comment]
> > 1606726660 @DreamStarX 加个qq我们讨论下？
> 
> 我提供给您EFI作者的QQ吧，我啥也不懂。2286191966，所在群聊为149664949

已更新

**Comment by DreamStarX** [comment]
谢谢大佬
