### ISSUE TITLE
Execuse me,Can not the Audio issue be solved?

### ISSUE THREAD

**Issue by zb2947244682** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#2]
I bought this notebook in recent day～～
So this problem puzzles me...
Thanks for your EFI~

**Comment by fuqiao1a** [comment]
兄弟方便留下邮箱交流下吗。

**Comment by fuqiao1a** [comment]
> I bought this notebook in recent day～～
> So this problem puzzles me...
> Thanks for your EFI~

https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only/issues/2#issue-495535002

**Comment by XenOriginal** [comment]
我也尝试过自己制作applealc补丁，无奈貌似还有问题

**Comment by zb2947244682** [comment]
> 我也尝试过自己制作applealc补丁，无奈貌似还有问题

是这台电脑问题，还是这款声卡本身不好弄？

**Comment by XenOriginal** [comment]
alc256相对比较困难

**Comment by zb2947244682** [comment]
> alc256相对比较困难

估计要弄一阵子了。

**Comment by zb2947244682** [comment]
> alc256相对比较困难

昨天找人弄了两三个小时声卡，真的是完全无解了。

**Comment by fuqiao1a** [comment]
> > alc256相对比较困难
> 
> 昨天找人弄了两三个小时声卡，真的是完全无解了。我这个ruby i5集显的就很奇怪了，装不上去，右边的那个USB好像不是2.0的，会卡在USB上

**Comment by XenOriginal** [comment]
> > alc256相对比较困难
> 
> 昨天找人弄了两三个小时声卡，真的是完全无解了。我这个ruby i5集显的就很奇怪了，装不上去，右边的那个USB好像不是2.0的，会卡在USB上

总线是3.0的引出来2.0，把ssdt-uiac drop了试试，这个是定制usb接口的

**Comment by MaximKiselev** [comment]
hey, any news？

**Comment by zb2947244682** [comment]
> hey, any news？

give up

**Comment by XenOriginal** [comment]
外放未解决，其余完美
