### ISSUE TITLE
网卡DW1820A支持使用吗

### ISSUE THREAD

**Issue by 985616770** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#22]
我没有买BCM94360CS2,而是使用了DW1820A网卡,之前用你的efi成功安装了10.15,现在换成openCore的话,影响吗?由于自己操作不当,想重新安装mac 看到换了引导程序,特有此问

**Comment by XenOriginal** [comment]
dw1820a肯定需要另外加kext，这个我倒没试过

**Comment by zszsj1231234** [comment]
已经尝试过，自己在config里面添加和clover一样的代码放进去kext可以使用。

**Comment by Mike-hd123** [comment]
换dw1820a网卡看可以完美支持吗，网上好像所。网速不行在mac下。

**Comment by zszsj1231234** [comment]
> 换dw1820a网卡看可以完美支持吗，网上好像所。网速不行在mac下。

我没测过速度，但是使用上貌似没什么问题，就是apple watch不能解锁貌似好像不是拆机卡就不行。

**Comment by Mike-hd123** [comment]
我还是买了BCM94360CS2，今天才发货，那个dw1820a好像说安装的时候要把网卡屏蔽在bios里面，可是小米笔记本就算了，否则只能把网卡拆下来才可以对吧。有没有这样的问题。会引导失败安装的时候。

**Comment by zszsj1231234** [comment]
> 我还是买了BCM94360CS2，今天才发货，那个dw1820a好像说安装的时候要把网卡屏蔽在bios里面，可是小米笔记本就算了，否则只能把网卡拆下来才可以对吧。有没有这样的问题。会引导失败安装的时候。

拆机卡不清楚好像是免驱的，dw1820的问题是无论是安装还是正常使用都需要config文件里面需要有pci设备信息在里面，不然进系统会卡死，如果会文本改config文件其实问题不大的，主要小米的bios没办法屏蔽。

**Comment by Mike-hd123** [comment]
你的dw1820是BCM94350ZAE还是BCM94356ZEPA50DX。

**Comment by Mike-hd123** [comment]
我们这个笔记本需要屏蔽针脚吗，兄弟要不加个qq好友github上面的太难了。我的qq是3161820061

**Comment by zszsj1231234** [comment]
> 我们这个笔记本需要屏蔽针脚吗，兄弟要不加个qq好友github上面的太难了。我的qq是3161820061

我的是BCM2045A0，不需要屏蔽针脚，config加了对应内容，驱动kext丢进引导就可以了。
