### ISSUE TITLE
一个关于网卡和外放的问题。

### ISSUE THREAD

**Issue by Mike-hd123** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#23]
网卡买BCM94360CS2后需要m.2转接卡吗，是m.2转接卡吗。你的笔记本装上转接卡和网卡后可以合起盖子吗。在opencore下有没有可能支持外放。

**Comment by Mike-hd123** [comment]
没有没有淘宝链接网卡的。

**Comment by XenOriginal** [comment]
94360cs2加转换卡就行 就插在原来的网卡位 转接卡剪短一点 然后螺丝可能不好上 但是使用不影响 不用对原机造成任何损坏

**Comment by XenOriginal** [comment]
外放目前没机会 除非硬改 机器内部内置一张蓝牙音频卡 把扬声器焊上去 然后mac连蓝牙实现

**Comment by Mike-hd123** [comment]
网卡win10驱动要自己安装吗，win10网速怎么样，有特别快的驱动可以分享一下吗win10的
