### ISSUE TITLE
oh!有关使用解锁CFG的问题

### ISSUE THREAD

**Issue by underline-ops** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#25]
emmmm,是小白一枚,用大佬的efi瞬间进入系统秒杀一切其他efi,但是最近更新了opencore之后尝试用了用,找不到CFG解锁的相关资料或者是脚本,小米官方也并没有给出bios的下载包.
所以要怎么解决TAT
请大佬支个招

**Comment by underline-ops** [comment]
转用opencore后进入系统会跑代码到最后显示
`Please go to https://panic.apple.com to report this panic`

**Comment by zszsj1231234** [comment]
这个项目你点进bios文件夹里面的DVMT_and_0xE2_fix文件夹点进去里面下面就有介绍ruby怎么解锁CFG和设置DVMT啊，东西都在这个项目里了下过来就可以直接用了，只有核显的版本设置DVMT会丢失睿频（Windows下mac下都会），至少我8130u是这样的，只能解锁cfg，需要改config文件里核显的部分。

**Comment by underline-ops** [comment]
> 这个项目你点进bios文件夹里面的DVMT_and_0xE2_fix文件夹点进去里面下面就有介绍ruby如何解锁CFG和设置DVMT啊，东西都在这个项目里了下过来就可以直接用了，只有核显的版本设置DVMT会丢失睿频（Windows下mac下都会），至少我8130u是这样的，只能解锁cfg，需要改配置文件里核显的部分。

太感谢了,谢谢!

**Comment by ghost** [comment]
> 转用opencore后进入系统会跑代码到最后显示
> `Please go to https://panic.apple.com to report this panic`

嗯 我也是，然后不是就失败了卡住进不去吗，就只能换用clover了
