### ISSUE TITLE
可以设置苹果热键启动吗，让电脑更接近白苹果。我试了好久都不行。

### ISSUE THREAD

**Issue by Mike-hd123** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#27]
如题

**Comment by XenOriginal** [comment]
OpenCore设置里面改成让苹果接手Boot试试，我暂时就不试了

**Comment by zszsj1231234** [comment]
你可以参考下我的，我是做了的。
关闭opencore-misc-boot-show picker，然后启用pollapplehotkeys。
在opencore-uefi下apple快捷键相关启用KeySupport。
然后确定uefi驱动有能驱动键盘的efi文件后重启后默认第一启动是opencore就能实现类似白苹果的启动了，你要更想点可以吧bios里的开盖唤醒开启，bootcamp下过来装上之类的。
我是用opencoreconfigurator编辑的，如果你是纯文本操作可能需要自己找下具体位置。

**Comment by Mike-hd123** [comment]
uefi驱动键盘的efi文件，你有吗直接分享过来呀，我好像没有，而且我也是应用写的配置。bios也是开盖唤醒，但是我按住alt没有反应直接开机。

**Comment by zszsj1231234** [comment]
> uefi驱动键盘的efi文件，你有吗直接分享过来呀，我好像没有，而且我也是应用写的配置。bios也是开盖唤醒，但是我按住alt没有反应直接开机。

你找下吧就是叫OpenUsbKbDxe.efi，如果你在mac设置里面设置启动磁盘成功的话重启在opencore自动引导你设置的盘的，Windows下只能从bootcamp改启动磁盘或者开机按住option键在引导界面选择分区引导，我记得option键好像是win键不是alt不太记得了
