### ISSUE TITLE
耳机输出问题

### ISSUE THREAD

**Issue by zero-sx** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#28]
我插入耳机时，必须保持 声音->输入->线路输入 的选中，且界面不能退出，耳机才能正常工作，请问该如何解决

**Comment by zero-sx** [comment]
![截屏2020-07-25 上午11 37 23](https://user-images.githubusercontent.com/33169723/88447977-810a9b80-ce6b-11ea-8a3b-be53de63b01e.png)

**Comment by underline-ops** [comment]
emmmm不是输出的问题嘛🙈

**Comment by underline-ops** [comment]
emmmm
试试调一下输出？

**Comment by underline-ops** [comment]
![image](https://user-images.githubusercontent.com/62235238/88448070-54a34f00-ce6c-11ea-88c9-a269300afff5.jpeg)

**Comment by zero-sx** [comment]
耳机刚插上是爆音的，这时候我点击一下上方图的线路输入，就恢复正常了。
如果不保持线路输入的选中，过十几秒就又会爆音。。。
