### ISSUE TITLE
频繁死机的问题

### ISSUE THREAD

**Issue by cqtangrenjie** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#29]
我这边是i5 8250u, mx110的版本，之前是用的大大的clover， 在10.14的版本很正常，后面升级到10.15后 引导也跟着大大换成opencore了， 从此后 就开始频繁死机，目前没有找到特定触发死机的情况，可能是浏览网页也可能是开发代码的时候就死机了一天大概能死机十几次，不知道是否是和我没有禁用独显或者是BIOS的设置有关？有什么办法能够排查问题吗？

**Comment by XenOriginal** [comment]
先禁用独显试试
