### ISSUE TITLE
Does this laptop really support NVME X4 SSD?

### ISSUE THREAD

**Issue by zb2947244682** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#3]
In officially speaking,this laptop just supports SATA SSD... 
![屏幕快照 2019-09-19 10 59 31](https://user-images.githubusercontent.com/49031758/65210095-a0f36500-dacc-11e9-852a-4709119a8c61.png)

**Comment by XenOriginal** [comment]
支持 supported

**Comment by zb2947244682** [comment]
> 支持 supported

好的～
