### ISSUE TITLE
The new Opencore efi can't compete sleep.

### ISSUE THREAD

**Issue by mch-go** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#33]
Thank you very much for your contribution, which enabled me to experience MacOS on Xiaomi laptop. I am of the same model as you, and there is no problem with Clover long ago. Since the use of OC, my computer's sleep state has not been normal. I have tried to modify it by myself, but still failed to achieve it. I'm currently the latest beta version of Big Sur.

**Comment by XenOriginal** [comment]
try this https://dortania.github.io/Getting-Started-With-ACPI/Universal/plug.html

**Comment by mch-go** [comment]
Thank you very much for your help, but I still failed to sleep on my laptop. I hope I can work this out in the future.So far, I've changed my network card to BCM94352z. It seems that now except the computer sleep, and there is no problem. I usually use headphones, not speakers.

**Comment by XenOriginal** [comment]
try Hackintool to change hibernate mode

**Comment by XenOriginal** [comment]
sudo pmset -a hibernatemode 3
