### ISSUE TITLE
Does i3-8130U version used?

### ISSUE THREAD

**Issue by bluehomewu** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#34]
![-7bd4dc99cac2b3c](https://user-images.githubusercontent.com/56945729/98465549-a6e26300-2204-11eb-99c1-bce3f5d5b1ae.jpg)

**Comment by XenOriginal** [comment]
Just use SSDTtime on Windows10 to generate SSDT-PLUG and replace it in ACPI folder

**Comment by XenOriginal** [comment]
https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#so-what-can-t-ssdttime-do

**Comment by bluehomewu** [comment]
> https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#so-what-can-t-ssdttime-do

Thank you so much 🥰.
