### ISSUE TITLE
How to change configs with  i7 edition?

### ISSUE THREAD

**Issue by colorfullee** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#35]
XiaoMi-Ruby-15.6 Without MX-150 ,I7 Edition,so that configs dosen't work on my computer

**Comment by XenOriginal** [comment]
Just use SSDTtime on Windows10 to generate SSDT-PLUG and replace it in ACPI folder

**Comment by XenOriginal** [comment]
https://dortania.github.io/Getting-Started-With-ACPI/ssdt-methods/ssdt-easy.html#so-what-can-t-ssdttime-do

**Comment by colorfullee** [comment]
I had tride generate all ACPI files on my own before, but I didn't have try to replace the SSDT-PLUG only with your ACPI folder, but it work well by the flowing EFI, here is the link:**https://github.com/ppyyr/Xiaomi-Ruby-15.6-i7-8550u**,but sth still work not well ,like the following : 
### can't get network by Huawei mobile usb network share, even the comfast' s CF-811AC driver, RJ45 only
### the Core graphics work not well when I use HDMI with other screen
_Last but not least ,Thanks for your help!_ I'll try it later!!

**Comment by XenOriginal** [comment]
Mac not native support android network share. Try HoRNDIS.
https://github.com/jwise/HoRNDIS
Intel Wireless Card can try ITLWM
https://github.com/OpenIntelWireless/itlwm
and HDMI need to use Hackintool to generate specific Framebuffer
https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html

**Comment by XenOriginal** [comment]
I recommend u change wireless card to bcm94360cs2. this is apple's native card
