### ISSUE TITLE
睡眠耗电问题！

### ISSUE THREAD

**Issue by hehe413** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#36]
请问一下，大家睡眠一晚上大概会掉多少电呀？

我的网卡是AX200，使用了Airportitlwm.kext。睡眠前关闭wifi。

系统是 10.14.6,  使用大佬的最新版本OC。

睡眠一晚上，掉电40%，这是正常的吗？

**Comment by XenOriginal** [comment]
sudo pmset -a hibernatemode 25
sudo pmset -b tcpkeepalive 0

**Comment by XenOriginal** [comment]
sudo pmset -a hibernatemode 3
这个稳定一点

**Comment by hehe413** [comment]
@XenOriginal 感谢您的回复。
sudo pmset -a hibernatemode 3 我设置的就是这个模式。

sudo pmset -a hibernatemode 25，设置为这种的话，好像进入不了睡眠，风扇一直在转的。

sudo pmset -b tcpkeepalive 0 这个和关闭wifi是一样的效果嘛？

大佬你那里睡眠一晚上，会消耗多少电量呢？

**Comment by XenOriginal** [comment]
我一般插电 没怎么测试过睡眠
