### ISSUE TITLE
可驱动声卡及外放的引导文件

### ISSUE THREAD

**Issue by DreamStarX** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#37]
哔哩哔哩小米Ruby黑果交流Q群（群号：782030947）一位朋友（QQ：294677899）分享的，他说他的i3白色款可以完美声音，搬运一下文件

[小米笔记本-小米 Ruby 15.6 2019版-i5 8250U+MX110+ALC256 OC 引导.rar.zip](https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only/files/5565235/-.Ruby.15.6.2019.-i5.8250U%2BMX110%2BALC256.OC.rar.zip)

**Comment by w19996** [comment]
我的i5还是不能外放啊

**Comment by DreamStarX** [comment]
> 我的i5还是不能外放啊

抱歉，不过你可以去问一下作者，上面有写

**Comment by XenOriginal** [comment]
也是用的applealc alcid=21 除非他自己定制了id21的配置，不然没啥区别，耳机是完美声音的
