### ISSUE TITLE
安装无线网卡后链接蓝牙耳机没有声音

### ISSUE THREAD

**Issue by Mike-hd123** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#38]
网卡是ax200

**Comment by Mike-hd123** [comment]
引导win10出错

**Comment by XenOriginal** [comment]
我这边引导win10正常的，错误要着重看一下ssdt有没有做好系统区分，不能用clover的ssdt

**Comment by XenOriginal** [comment]
ax200看一下itlwm驱动的情况，去那边反应一下，kext和引导win10没关系的，只有acpi的修改才会有影响
