### ISSUE TITLE
外放硬改

### ISSUE THREAD

**Issue by w19996** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#39]
看您图片，硬改的话是不是一直要从电脑内部伸出来线连接usb接口啊，能不能在电脑内部连接供电呢

**Comment by XenOriginal** [comment]
可以啊 找个5v焊一下 或者12v转一下

**Comment by w19996** [comment]
> 可以啊 找个5v焊一下 或者12v转一下

您可以说一下焊接在哪个地方吗，哪个地方有5V，我不太懂，也不敢随便焊，怕把主板搞坏了

**Comment by XenOriginal** [comment]
拿万用表测
