### ISSUE TITLE
Mi lite i5 with mx110 problem

### ISSUE THREAD

**Issue by haltaction** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#41]
Hello, first of all thanks for you work.
But I have an issue and maybe you could help me. I'm trying to use your config with open core, create installer from Linux and Macos, several versions of MacOS, but got the next error on booting proccess:
![image](https://user-images.githubusercontent.com/5079045/105611510-84e98d00-5dbe-11eb-9c29-2adc9f04c333.png)
I suppose it because of my GPU, tried to disable via boot args `-wegnoegpu`, but no luck.
With https://github.com/daliansky/XiaoMi-Pro-Hackintosh config it installs, but with hardware problems.
Could you answer what is the possible solution for it?

**Comment by XenOriginal** [comment]
Please unlock msr and dvmt under windows, tools are in BIOS folder.

**Comment by haltaction** [comment]
Thanks for reply
So, `Use scripts unlock CFG and set DVMT - Recommend` is actually required for the current config, yes?
Because I tried to do it - and after the first attempt I had video freezes, a non-working keyboard in Windows - so I reset BIOS for fixing it.

So current bios unlock scripts completely compatible with mi notebook ruby and don't cause any troubles with working Windows, and required for current setup, am I right?

**Comment by XenOriginal** [comment]
yes

**Comment by XenOriginal** [comment]
You can try add patches without modify bios.

1. Add DVMT patches

- <b>For both Clover and OC users:</b>
  - Open `/EFI/CLOVER (or OC)/config.plist`, add the following code under DeviceProperties/Add/PciRoot(0x0)/Pci(0x2,0x0):
```
<key>framebuffer-fbmem</key>
<data>AACQAA==</data>
<key>framebuffer-stolenmem</key>
<data>AAAwAQ==</data>
```

2. Add OC MSR 0xE2 patch

Open `/EFI/OC/config.plist`, find the following code:
```
<key>AppleCpuPmCfgLock</key>
<false/>
<key>AppleXcpmCfgLock</key>
<false/>
```
Change to:
```
<key>AppleCpuPmCfgLock</key>
<true/>
<key>AppleXcpmCfgLock</key>
<true/>
```

**Comment by haltaction** [comment]
Got it, thanks.
