### ISSUE TITLE
Mi Ruby 15.6 with MX110 boot failed

### ISSUE THREAD

**Issue by hydrati** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#42]
Error log:
![IMG_20210501_234729](https://user-images.githubusercontent.com/29159838/116787726-5e7f7000-aad8-11eb-9e42-37bdd6e0dcb5.jpg)

Used `AirportItlwm` & `IntelBluetoothFirmware`

Replaced Wireless Network Cards from Realtek to Intel AX200

**Comment by Mike-hd123** [comment]
I have fork,solve

**Comment by Mike-hd123** [comment]
Brightness adjustment fails in the latest edition

**Comment by hydrati** [comment]
@Mike-hd123  thanks, I'll try again later.

**Comment by Mike-hd123** [comment]
So, is your backlight working? What version are you?
