### ISSUE TITLE
my laptop can sleep but can't awaken, What's wrong did I do？

### ISSUE THREAD

**Issue by lightzhu** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#46]

**Comment by Missyouag** [comment]
are your screen light?it's [whatevergreen]([url](url)) params err,u can add boot-args like this:igfxonln=1 igfxfcmsfbs=0x010203 -cdfon

u can do best by reading [WhateverGreen](https://github.com/acidanthera/WhateverGreen)

**Comment by lightzhu** [comment]
现在是盒盖睡眠之后唤醒可以亮屏，但是USB失效，必须重启@Missyouag

**Comment by XenOriginal** [comment]
Delete SSDT-UIAC and USBPorts.kext, reconstruct SSDT-PLUG.aml by conferring Dortania.github.io . Then you can using Propertree refresh the kexts and hotpatchs list.

**Comment by lightzhu** [comment]
> Delete SSDT-UIAC and USBPorts.kext, reconstruct SSDT-PLUG.aml by conferring Dortania.github.io . Then you can using Propertree refresh the kexts and hotpatchs list.

3Q ,现在凑合能用，有时间再折腾一次

**Comment by lightzhu** [comment]
none
