### ISSUE TITLE
系统识别出的显卡型号是hd620而非uhd620

### ISSUE THREAD

**Issue by E79180** [XenOriginal/XiaoMi-Ruby-15.6-UMA-only#8]

**Comment by stevezz3** [comment]
@WiardYu 删除config里的https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only/blob/master/CLOVER/config.plist#L515 和 https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only/blob/master/CLOVER/config.plist#L516 即可。
